all: roadmap bib

bib:
	xelatex cs7485
	bibtex  cs7485
	xelatex cs7485
	xelatex cs7485

short:
	xelatex cs7485

roadmap:
	xelatex roadmap.tex

clean:
	rm *.log
	rm *.out
	rm *.aux
	rm *.bbl
	rm *.blg
	rm *.pdf
